name: Hourly Weather Sync

on:
  schedule:
    # Run at minute 0 of every hour
    - cron: '0 * * * *'
  workflow_dispatch: # run manually with a button

jobs:
  build:
    runs-on: ubuntu-latest #faster than windows

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run weather script
        working-directory: ./Day1
        run: python weather.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add weather.csv
          git commit -m "Automated weather update" || exit 0
          git push